/**
 * The release whose copy is compiled into this bundle.
 *
 * ⚠️ GENERATED by `scripts/sync-translations.mjs` — do not edit by hand.
 *
 * At runtime the client compares this hash against the live manifest's
 * `release.contentHash` and, when they match, fetches no blobs at all.
 */
export const BASELINE_CONTENT_HASH: string | null = null;

/** Release version the baseline came from; `null` when never synced. */
export const BASELINE_RELEASE_VERSION: number | null = null;

/** When the sync ran, ISO-8601. Diagnostics only — never used for freshness. */
export const BASELINE_SYNCED_AT: string | null = null;

/**
 * The `ETag` header value as received. Used ONLY as an `If-None-Match` token by
 * the build-time sync script.
 *
 * ⚠️ THIS IS NOT `BASELINE_CONTENT_HASH` WITH THE PREFIX STRIPPED.
 *
 *     BASELINE_MANIFEST_ETAG !== BASELINE_CONTENT_HASH.slice(7)   // always
 *
 * They hash different things. `contentHash` is `sha256:<hex>` over the RELEASE
 * CONTENT and answers "is my bundle stale". The ETag is bare hex identifying the
 * MANIFEST DOCUMENT. Any code comparing them is permanently false, and the
 * symptom looks exactly like "the cache never hits".
 */
export const BASELINE_MANIFEST_ETAG: string | null = null;
