import type { Metadata } from 'next';
import { getTranslations, setRequestLocale } from 'next-intl/server';

import { locales } from '@/i18n/routing';
import { Section } from '@/components/ui';
import credits from '../../../../content/credits.json';

export function generateStaticParams() {
    return locales.map((locale) => ({ locale }));
}

export async function generateMetadata({
    params,
}: {
    params: Promise<{ locale: string }>;
}): Promise<Metadata> {
    const { locale } = await params;
    const t = await getTranslations({ locale, namespace: 'about.meta' });
    return { title: t('title'), description: t('description') };
}

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) {
    const { locale } = await params;
    setRequestLocale(locale);
    const t = await getTranslations('about');

    return (
        <Section width="narrow" pad="top">
            <h1 className="font-serif text-4xl text-ink">{t('title')}</h1>
            <p className="mt-4 leading-relaxed text-ink-soft">{t('body')}</p>

            <h2 className="mt-10 font-serif text-2xl text-ink">{t('why.title')}</h2>
            <p className="mt-3 leading-relaxed text-ink-soft">{t('why.body')}</p>

            <h2 className="mt-10 font-serif text-2xl text-ink">{t('credits.title')}</h2>
            <p className="mt-3 text-ink-soft">{t('credits.body')}</p>
            {/*
              * Generated by scripts/fetch-photos.mjs from the API response for
              * each photo id, never typed by hand — an attribution somebody
              * transcribed is an attribution that outlives the photo it was
              * copied from.
              */}
            <ul className="mt-5 grid gap-2 text-sm sm:grid-cols-2">
                {credits.photos.map((photo) => (
                    <li key={photo.id}>
                        <a
                            href={photo.photoUrl}
                            rel="noopener noreferrer nofollow"
                            target="_blank"
                            className="text-ink-soft underline decoration-sand-400 underline-offset-4 transition hover:text-sea-deep"
                        >
                            {photo.photographer}
                        </a>
                        <span className="text-sand-600"> · {photo.license}</span>
                    </li>
                ))}
            </ul>
        </Section>
    );
}
